### ISSUE TITLE
RabbitMQ Health Indicator fails to instantiate when multiple servers are configured

### ISSUE THREAD

**Issue by kirans9731** [micronaut-projects/micronaut-rabbitmq#168] opened 2020-12-02 20:13 UTC
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Include rabbitmq and management dependencies
2. Configure more than one servers in application configuration

```
rabbitmq:
  automatic-recovery-enabled: true
  requested-heartbeat: 1
  servers:
    one:
      uri: amqp://guest:guest@localhost:5672
    two:
      uri: amqp://guest:guest@localhost:5672
```

3. Start the application, below exception is thrown

```
14:58:06.410 [scheduled-executor-thread-1] ERROR i.m.s.DefaultTaskExceptionHandler - Error invoking scheduled task Failed to inject value for parameter [connection] of class: io.micronaut.rabbitmq.health.RabbitMQHealthIndicator

Message: Multiple possible bean candidates found: [com.rabbitmq.client.Connection, com.rabbitmq.client.Connection]
Path Taken: new HealthMonitorTask(CurrentHealthStatus currentHealthStatus,[List healthIndicators]) --> new RabbitMQHealthIndicator([Connection connection])
io.micronaut.context.exceptions.DependencyInjectionException: Failed to inject value for parameter [connection] of class: io.micronaut.rabbitmq.health.RabbitMQHealthIndicator

Message: Multiple possible bean candidates found: [com.rabbitmq.client.Connection, com.rabbitmq.client.Connection]
Path Taken: new HealthMonitorTask(CurrentHealthStatus currentHealthStatus,[List healthIndicators]) --> new RabbitMQHealthIndicator([Connection connection])
	at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:1035)
	at io.micronaut.rabbitmq.health.$RabbitMQHealthIndicatorDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1898)
	at io.micronaut.context.DefaultBeanContext.addCandidateToList(DefaultBeanContext.java:2990)
	at io.micronaut.context.DefaultBeanContext.getBeansOfTypeInternal(DefaultBeanContext.java:2891)
	at io.micronaut.context.DefaultBeanContext.getBeansOfType(DefaultBeanContext.java:1045)
	at io.micronaut.context.AbstractBeanDefinition.lambda$getBeansOfTypeForConstructorArgument$9(AbstractBeanDefinition.java:1143)
	at io.micronaut.context.AbstractBeanDefinition.resolveBeanWithGenericsFromConstructorArgument(AbstractBeanDefinition.java:1820)
	at io.micronaut.context.AbstractBeanDefinition.getBeansOfTypeForConstructorArgument(AbstractBeanDefinition.java:1138)
	at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:990)
	at io.micronaut.management.health.monitor.$HealthMonitorTaskDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1898)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingletonInternal(DefaultBeanContext.java:2647)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2633)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2305)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2279)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:721)
	at io.micronaut.scheduling.processor.ScheduledMethodProcessor.lambda$process$5(ScheduledMethodProcessor.java:123)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: io.micronaut.context.exceptions.NonUniqueBeanException: Multiple possible bean candidates found: [com.rabbitmq.client.Connection, com.rabbitmq.client.Connection]
	at io.micronaut.context.DefaultBeanContext.findConcreteCandidate(DefaultBeanContext.java:1987)
	at io.micronaut.context.DefaultApplicationContext.findConcreteCandidate(DefaultApplicationContext.java:434)
	at io.micronaut.context.DefaultBeanContext.lastChanceResolve(DefaultBeanContext.java:2624)
	at io.micronaut.context.DefaultBeanContext.findConcreteCandidateNoCache(DefaultBeanContext.java:2548)
	at io.micronaut.context.DefaultBeanContext.findConcreteCandidate(DefaultBeanContext.java:2478)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2259)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1245)
	at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:1013)
	... 23 common frames omitted
```

### Expected Behaviour

RabbitMQHealthIndicator should be instantiated properly and the health check should work

### Actual Behaviour

Above exception is thrown

### Environment Information

- **Operating System**: macOS Catalina
- **Micronaut Version:** 2.2.0
- **JDK Version:** Corretto-11.0.8.10.1

### Example Application

https://github.com/kirans9731/micronaut-rabbitmq-demo-bug

**Comment by kirans9731** [comment] 2020-12-03 15:41
Same issue identified with 2.1.4

**Comment by jameskleeh** [comment] 2020-12-03 19:06
Duplicate of #128

**Closed by jameskleeh** 2020-12-03 19:06 UTC
