### ISSUE TITLE
ExecutorConfiguration Duplicate

### ISSUE THREAD

**Issue by ctoestreich** [micronaut-projects/micronaut-rabbitmq#18] opened 2019-07-09 00:50 UTC
When including both `micronaut-kafka-streams` and `micronaut-rabbitmq` there is a duplicate bean wired.  This may not be standard, but the error is not helpful or graceful.

https://github.com/tardisoft/executorissue

```

io.micronaut.context.exceptions.DependencyInjectionException: Failed to inject value for parameter [executorConfiguration] of class: java.util.concurrent.ExecutorService

Message: Multiple possible bean candidates found: [io.micronaut.scheduling.executor.ExecutorConfiguration, io.micronaut.scheduling.executor.ExecutorConfiguration]
Path Taken: new KafkaConsumerProcessor([ExecutorService executorService],ApplicationConfiguration applicationConfiguration,BeanContext beanContext,AbstractKafkaConsumerConfiguration defaultConsumerConfiguration,ConsumerRecordBinderRegistry binderRegistry,BatchConsumerRecordsBinderRegistry batchBinderRegistry,SerdeRegistry serdeRegistry,ProducerRegistry producerRegistry,KafkaListenerExceptionHandler exceptionHandler) --> ExecutorService.executorService([ExecutorConfiguration executorConfiguration])

	at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:990)
	at io.micronaut.context.BeanDefinitionDelegate.build(BeanDefinitionDelegate.java:205)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1494)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2174)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:1852)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:1832)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:997)
	at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:982)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1494)
	at io.micronaut.context.DefaultBeanContext.addCandidateToList(DefaultBeanContext.java:2507)
	at io.micronaut.context.DefaultBeanContext.getBeansOfTypeInternal(DefaultBeanContext.java:2407)
	at io.micronaut.context.DefaultBeanContext.streamOfType(DefaultBeanContext.java:615)
	at io.micronaut.context.DefaultBeanContext.streamOfType(DefaultBeanContext.java:602)
	at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1228)
	at io.micronaut.context.DefaultApplicationContext.initializeContext(DefaultApplicationContext.java:236)
	at io.micronaut.context.DefaultBeanContext.readAllBeanDefinitionClasses(DefaultBeanContext.java:2325)
	at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:199)
	at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:187)
	at io.micronaut.context.ApplicationContextBuilder.start(ApplicationContextBuilder.java:150)
	at io.micronaut.context.ApplicationContext.run(ApplicationContext.java:181)
	at io.micronaut.context.ApplicationContext.run(ApplicationContext.java:163)
	at kafka.streams.issue.BatchManualOffsetCommitSpec.$spock_initializeSharedFields(BatchManualOffsetCommitSpec.groovy:25)
Caused by: io.micronaut.context.exceptions.NonUniqueBeanException: Multiple possible bean candidates found: [io.micronaut.scheduling.executor.ExecutorConfiguration, io.micronaut.scheduling.executor.ExecutorConfiguration]
	at io.micronaut.context.DefaultBeanContext.findConcreteCandidate(DefaultBeanContext.java:1585)
	at io.micronaut.context.DefaultApplicationContext.findConcreteCandidate(DefaultApplicationContext.java:395)
	at io.micronaut.context.DefaultBeanContext.lastChanceResolve(DefaultBeanContext.java:2156)
	at io.micronaut.context.DefaultBeanContext.findConcreteCandidateNoCache(DefaultBeanContext.java:2069)
	at io.micronaut.context.DefaultBeanContext.lambda$findConcreteCandidate$54(DefaultBeanContext.java:2031)
	at io.micronaut.core.util.clhm.ConcurrentLinkedHashMap.lambda$compute$0(ConcurrentLinkedHashMap.java:721)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
	at io.micronaut.core.util.clhm.ConcurrentLinkedHashMap.compute(ConcurrentLinkedHashMap.java:733)
	at io.micronaut.core.util.clhm.ConcurrentLinkedHashMap.computeIfAbsent(ConcurrentLinkedHashMap.java:710)
	at io.micronaut.context.DefaultBeanContext.findConcreteCandidate(DefaultBeanContext.java:2030)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:1807)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:997)
	at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:982)
	... 21 more
```

**Comment by jameskleeh** [comment] 2019-07-17 15:48
Tried looking into this but the project must not be configured correctly. One of the dependencies can't be resolved.

**Comment by Amcharde** [comment] 2019-07-18 10:02
Faced same issue, created project using below cli and added @RabbitListener
mn create-app test.example.rabbitmqkafka --lang kotlin  --build maven --features=spek,config-consul,discovery-consul,rabbitmq,kafka,file-watch

Caused by: io.micronaut.context.exceptions.NonUniqueBeanException: Multiple possible bean candidates found: [io.micronaut.scheduling.executor.ExecutorConfiguration, io.micronaut.scheduling.executor.ExecutorConfiguration]
	at io.micronaut.context.DefaultBeanContext.findConcreteCandidate(DefaultBeanContext.java:1585)
	at io.micronaut.context.DefaultApplicationContext.findConcreteCandidate(DefaultApplicationContext.java:395)
	at io.micronaut.context.DefaultBeanContext.lastChanceResolve(DefaultBeanContext.java:2156)
	at io.micronaut.context.DefaultBeanContext.findConcreteCandidateNoCache(DefaultBeanContext.java:2069)
	at io.micronaut.context.DefaultBeanContext.lambda$findConcreteCandidate$54(DefaultBeanContext.java:2031)
	at io.micronaut.core.util.clhm.ConcurrentLinkedHashMap.lambda$compute$0(ConcurrentLinkedHashMap.java:721)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
	at io.micronaut.core.util.clhm.ConcurrentLinkedHashMap.compute(ConcurrentLinkedHashMap.java:733)
	at io.micronaut.core.util.clhm.ConcurrentLinkedHashMap.computeIfAbsent(ConcurrentLinkedHashMap.java:710)
	at io.micronaut.context.DefaultBeanContext.findConcreteCandidate(DefaultBeanContext.java:2030)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:1807)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:997)
	at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:982)
	... 38 common frames omitted

**Comment by ctoestreich** [comment] 2019-07-18 15:48
@jameskleeh I changed the project to something similar akin to what @Amcharde posted.  Simply run the application to see the issue on boot

https://github.com/tardisoft/executorissue

**Comment by jameskleeh** [comment] 2019-07-18 16:17
So this is because both Kafka and Micronaut provide "consumer" executor services if they are not configured. I don't think I could remove either of those beans because then in isolation neither of them would work.

Luckily both of the beans are disabled if the configuration for the consumer executor is manually supplied. That means if you supply the configuration for the consumer thread pool yourself, then neither bean will be enabled and the default one will be used.

Adding the below config will allow the application to work

```
micronaut:
  executors:
    consumer:
      type: FIXED
```

Beyond that I don't know what else I could do to fix the issue. I'll close it for now but if you have any suggestions I'd be happy to re-open it.

**Closed by jameskleeh** 2019-07-18 16:17 UTC
Labels: awaiting feedback

**Comment by ctoestreich** [comment] 2019-07-18 16:54
@jameskleeh Do you have more details to the docs on that config you provided?

**Comment by jameskleeh** [comment] 2019-07-18 17:07
https://docs.micronaut.io/latest/guide/index.html#io.micronaut.scheduling.executor.UserExecutorConfiguration

https://micronaut-projects.github.io/micronaut-rabbitmq/snapshot/guide/index.html#consumerExecutor
