### ISSUE TITLE
Autorecovery is not triggered against clustered Rabbitmq instances

### ISSUE THREAD

**Issue by oscarfh** [micronaut-projects/micronaut-rabbitmq#210] opened 2021-02-24 21:22 UTC
When using a micronaut app against a clustered rabbitmq setup, the app does not resuming consumption if the rabbitmq node that it is connected to fails (restarts).

Given a clustered RabbitMQ with at least 2 instances and a Micronaut app connected to a load balancer to these rabbitMQ nodes. The consumer creates a non-ha durable queue which is assigned to a rabbitmq node. If this node is restarted, the micronaut app is not able to resume consuming and has to be restarted.

### Steps to Reproduce

1. in a minikube cluster, run:
`helm install bitnami/rabbitmq --name testrabbit --set replicaCount=3,auth.password="RABBITMQ_PASSWORD",auth.erlangCookie="RABBITMQ_ERLANG_COOKIE"`
2. Port forward the service (and not a single node): `kubectl port-forward --namespace default svc/testrabbit-rabbitmq 5672:5672`
3. Startup a Micronaut rabbitmq client listening on port 5672 that listens on a durable queue
4. Manually (using the management ui) publish a message and notice that it reaches the listener
5. In the management ui (queue tab), you can see which node the queue is assigned to. Restart the node (`kubectl delete pod ..`)
6. When the node comes back, publish a new message
7. Notice that the message does not arrive to the listener

ps: Sometimes error messages about connection resets are logged, not always

### Expected Behaviour

When the rabbit node comes back, it the consumer should consume messages without the need of restart.

### Actual Behaviour

The consumer hangs: nothing is consumed, but the health indicator still shows "UP".

### More details
I could notice that the recovery mechanism on `com.rabbitmq.client.impl.recovery.AutorecoveringConnection` is triggered by `com.rabbitmq.client.impl.AMQConnection#notifyRecoveryCanBeginListeners`, which, in turn, is called by `com.rabbitmq.client.impl.AMQConnection#doFinalShutdown`.
The `com.rabbitmq.client.impl.AMQConnection#doFinalShutdown` method is called either when 1- there is an error, 2- when the heartbeat fails, 3- when there is an unexpected exception when reading a frame 4- when there is a problem in the NioLoop.
It seems that, because we are using a clustered rabbitmq, there is no issue with the connection (as far as I understood, rabbit will send a `CANCEL` message, which is be handler by `io.micronaut.rabbitmq.intercept.DefaultConsumer` in the `io.micronaut.rabbitmq.intercept.DefaultConsumer#handleCancel` which is then forwarded to `io.micronaut.rabbitmq.intercept.DefaultConsumer#handleTerminate`.

At this point, the connection is open, the consumer failed, you might be able to see the message `The channel was terminated.  Automatic recovery attempt is underway for consumer xyz` from `io.micronaut.rabbitmq.intercept.RabbitMQConsumerAdvice`, but it does not perform the operation, but relies on the above mentioned mechanism to do so.

I have a fix in which I close the connection and call manually `com.rabbitmq.client.impl.AMQConnection#doFinalShutdown` when such a problem happens. This has been proven to work on my very specific tests. If you agree that this is an acceptable solution, I would love to make a patch and create a PR for this.

### Environment Information

- **Operating System**: ubuntu 18.04
- **Micronaut Version:** 2.3.3
- **JDK Version:** 15

**Comment by graemerocher** [comment] 2021-02-24 21:32
PRs welcome!

**Comment by oscarfh** [comment] 2021-02-25 21:50
@graemerocher I created a PR for that. I am not very happy with the code quality (see come comments on that in the PR). But this was what I could work out in the time and knowledge that I had. I will be happy to hear your feedback.

**Comment by michaelklishin** [comment] 2021-03-04 10:37
RabbitMQ clients that support automatic connection recovery do so, well, when *connections* fail. They by design do not try to recover from [channel exceptions](https://www.rabbitmq.com/channels.html#error-handling) or [consumer cancelation notifications](https://www.rabbitmq.com/consumer-cancel.html), by design. Those are up to application developers to handle.

If a node is shut down, all of its client connections will be closed by definition: the kernel will close all of their TCP sockets.
Which, if you provide a list of hosts to try to your `ConnectionFactory`, will lead to a reconnection to a different node with all of the topology restored.

If you are getting a cancellation message, it means that the queue you were consuming from was deleted. My best guess is that you try to react to that somehow.

I cannot suggest what may be going on without any logs but this feature has been around in the Java client for almost 8 years.
Before you do any more testing, consider that [two node clusters are NOT supported](https://www.rabbitmq.com/clustering.html#node-count).

**Comment by oscarfh** [comment] 2021-03-04 14:27
@michaelklishin thanks a lot for the explanation. 
@jameskleeh I would propose to reject this issue.

**Closed** 2021-03-04 15:23 UTC
Labels: status: awaiting third-party
